services:
    #CHAT
    #Repositories
    Chat.ChatRepository:
        class: ../../../../application/Chat/infrastructure/persistence/MongoChatRepository
        arguments: ['@Shared.DataRepository']
    #Use cases
    Chat.CreateChat:
        class: ../../../../application/Chat/application/create/CreateChat
        arguments: ['@Chat.ChatRepository']

    Chat.SearchChat:
        class: ../../../../application/Chat/application/search/SearchChat
        arguments: ['@Chat.ChatRepository']

    Chat.UpdateChat:
        class: ../../../../application/Chat/application/update/UpdateChat
        arguments: ['@Chat.ChatRepository']
    #Controllers
    #Chat.CreateChatController:
        #class: ../../../../backend/controllers/Chat/CreateChatController
        #arguments: []
    #CHAT MESSAGE
    #Repository
    ChatMessage.ChatMessageRepository:
        class: ../../../../application/ChatMessage/infrastructure/persistence/MongoChatMessageRepository
        arguments: ['@Shared.DataRepository']
    #Use cases
    ChatMessage.CreateChatMessage:
        class: ../../../../application/ChatMessage/application/create/CreateChatMessage
        arguments: ['@ChatMessage.ChatMessageRepository']
    #Controllers
    ChatMessage.ChatMessageController:
        class: ../../../../backend/controllers/Chat/ChatMessageController
        arguments: []

