services:
    #Repositories
    Users.UserRepository:
        class: ../../../../application/User/infrastructure/Persistence/MongoUsersRepository
        arguments: ["@Shared.DataRepository"]
    #Controllers
    Users.Controllers.UserFinderController:
        class: ../../../../backend/controllers/User/UserFinderController
        arguments: []
    Users.Controllers.UserRegisterController:
        class: ../../../../backend/controllers/User/UserRegisterController
        arguments: []
    #Use cases
    Users.UseCases.UserFinder:
        class: ../../../../application/User/application/find/UserFinder
        arguments: ["@Users.UserRepository"]
    Users.UseCases.UserCreator:
        class: ../../../../application/User/application/create/UserCreator
        arguments: ["@Users.UserRepository"]
