services:
    #Repositories
    Users.UserRepository:
        class: ../../../../application/User/infrastructure/persistence/MongoUsersRepository
        arguments: ["@Shared.DataRepository"]
    #Controllers
    Users.Controllers.UserRegisterController:
        class: ../../../../backend\controllers\User\UserRegisterController
        arguments: ["@Users.UserRepository"]