services:
    #Repositories
    IoTDevice.IoTDeviceRepository:
        class: ../../../../application/IoTDevice/infrastructure/persistence/MongoIoTDeviceRepository
        arguments: ['@Shared.DataRepository']
    IoTDevice.IoTDeviceDataRepository:
        class: ../../../../application/IoTDeviceData/infrastructure/persistence/MongoIoTDeviceDataRepository
        arguments: ['@Shared.DataRepository']
    #Controllers
    IoTDevice.IoTDeviceCreateController:
        class: ../../../../backend/controllers/IoTDevice/IoTDeviceCreateController
        arguments: []
    IoTDevice.IoTDeviceFindController:
        class: ../../../../backend/controllers/IoTDevice/IoTDeviceFindController
        arguments: []
    IoTDevice.IoTDeviceLinkController:
        class: ../../../../backend/controllers/IoTDevice/IoTDeviceLinkController
        arguments: []
    IoTDevice.IoTDeviceDataSearchController:
        class: ../../../../backend/controllers/IoTDeviceData/IoTDeviceDataSearchController
        arguments: []
    IoTDevice.IoTDeviceDataCreateController:
        class: ../../../../backend/controllers/IoTDeviceData/IoTDeviceDataCreateController
        arguments: []
    #Use cases
    IoTDevice.CreateIoTDevice:
        class: ../../../../application/IoTDevice/application/create/CreateIoTDevice
        arguments: ['@IoTDevice.IoTDeviceRepository']
    IoTDevice.FindIoTDevice:
        class: ../../../../application/IoTDevice/application/find/FindIoTDevice
        arguments: ['@Users.UserRepository', '@IoTDevice.IoTDeviceRepository']
    IoTDevice.LinkIoTDevice:
        class: ../../../../application/IoTDevice/application/link/LinkIoTDevice
        arguments: ['@Users.UserRepository', '@IoTDevice.IoTDeviceRepository']
    IoTDevice.UpdateIoTDevice:
        class: ../../../../application/IoTDevice/application/update/UpdateIoTDevice
        arguments: ['@Users.UserRepository', '@IoTDevice.IoTDeviceRepository']
    IoTDevice.SearchIoTDeviceData:
        class: ../../../../application/IoTDeviceData/application/search/SearchIoTDeviceData
        arguments: ['@IoTDevice.IoTDeviceDataRepository']
    IoTDevice.CreateIoTDeviceData:
        class: ../../../../application/IoTDeviceData/application/create/CreateIoTDeviceData
        arguments: ['@IoTDevice.IoTDeviceDataRepository']
