services:
    #Repositories
    UserAuthentication.UserAuthenticationRepository:
        class: ../../../../application/UserAuthentication/infrastructure/persistence/MongoUsersAuthRepository
        arguments: ["@Shared.DataRepository"]
    #Use cases
    UserAuthentication.UseCases.UserAuthentication:
        class: ../../../../application/UserAuthentication/application/authentication/UserAuthentication
        arguments: ["@Users.UserRepository", "@UserAuthentication.UserAuthenticationRepository"]
    #Controllers
    UserAuthentication.Controllers.UserAuthenticationController:
        class: ../../../../backend/controllers/UserAuthentication/UserAuthenticationController
        arguments: []