imports:
    - { resource: ./modules/Shared/application.yaml }
    - { resource: ./modules/Users/application.yaml }
    - { resource: ./modules/IoTDevice/application.yaml }
    - { resource: ./modules/UserAuthentication/application.yaml }
    - { resource: ./modules/Subscriptions/application.yaml }
