services:
    #Repositories
    Notifications.NotificationsRepository:
        class: ../../../../application/Notifications/infrastructure/persistence/MongoNotificationsRepository
        arguments: ['@Shared.DataRepository']
    #Use cases
    Notifications.SearchNotification:
        class: ../../../../application/Notifications/application/search/SearchNotification
        arguments: ['@Notifications.NotificationsRepository']
    Notifications.CreateNotification:
        class: ../../../../application/Notifications/application/create/CreateNotification
        arguments: ['@Notifications.NotificationsRepository']
    #Controllers
    Notifications.NotificationsController:
        class: ../../../../backend/controllers/Notifications/NotificationsController
        arguments: []

    #NotificationSettings
    #Repositories
    NotificationSettings.NotificationSettingsRepository:
        class: ../../../../application/NotificationSettings/infrastructure/persistence/MongoNotificationSettingsRepository
        arguments: ['@Shared.DataRepository']
    #Use cases
    NotificationSettings.SearchNotificationSettings:
        class: ../../../../application/NotificationSettings/application/search/SearchNotificationSettings
        arguments: ['NotificationSettings.NotificationSettingsRepository']
    NotificationSettings.CreateNotificationSettings:
        class: ../../../../application/NotificationSettings/application/create/CreateNotificationSettings
        arguments: ['@NotificationSettings.NotificationSettingsRepository']
    #Controllers
    NotificationSettings.NotificationSettingsController:
        class: ../../../../backend/controllers/NotificationSettings/NotificationSettingsController
        arguments: []